# Generated by Django 3.0.6 on 2020-05-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSIApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='No',
        ),
        migrations.AddField(
            model_name='student',
            name='Pass',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Re_Pass',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
