# Generated by Django 3.0.6 on 2020-06-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSIApp', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
